services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6399:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass dddeYVX7EwVmmxKPCDmwMdddaaatyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local